"use client";

import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { useCustomWallet } from "@/contexts/CustomWallet";
import { ExternalLink } from "lucide-react";

export default function ProfilePopover() {
  const { isConnected, logout, redirectToAuthUrl, emailAddress, address } =
    useCustomWallet();

  if (isConnected) {
    return (
      <Popover>
        <PopoverTrigger asChild>
          <Button className="hidden sm:block" variant={"secondary"}>
            {emailAddress}
          </Button>
        </PopoverTrigger>
        <PopoverContent className="w-80" >
          <Card className="border-none shadow-none">
            <CardHeader>
              <CardTitle>Account Info</CardTitle>
              <CardDescription>
                View the account generated by Enoki's zkLogin flow.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="flex flex-row gap-1 items-center">
                <span>Address: </span>
                <div className="flex flex-row gap-1">
                  <span>{`${address?.slice(0, 5)}...${address?.slice(-5)}`}</span>
                  <a
                    href={`https://suiscan.xyz/testnet/account/${address}`}
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    <ExternalLink width={12} />
                  </a>
                </div>
              </div>
            </CardContent>
            <CardFooter>
              <Button
                variant={"destructive"}
                className="w-full"
                onClick={logout}
              >
                Logout
              </Button>
            </CardFooter>
          </Card>
        </PopoverContent>
      </Popover>
    );
  }

  return (
    <Button
      onClick={redirectToAuthUrl}
      className="bg-blue-600 hover:bg-blue-700 text-white"
    >
      Sign in with Google
    </Button>
  );
}
